In [0]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

FileNotFoundError: ignored

In [0]:
import bq_helper

from bq_helper import BigQueryHelper
# https://www.kaggle.com/sohier/introduction-to-the-bq-helper-package
stackOverflow = bq_helper.BigQueryHelper(active_project="bigquery-public-data",
                                   dataset_name="stackoverflow")

ModuleNotFoundError: ignored

In [0]:
bq_assistant = BigQueryHelper("bigquery-public-data", "stackoverflow")
bq_assistant.list_tables()

Using Kaggle's public dataset BigQuery integration.

['badges',
 'comments',
 'post_history',
 'post_links',
 'posts_answers',
 'posts_moderator_nomination',
 'posts_orphaned_tag_wiki',
 'posts_privilege_wiki',
 'posts_questions',
 'posts_tag_wiki',
 'posts_tag_wiki_excerpt',
 'posts_wiki_placeholder',
 'stackoverflow_posts',
 'tags',
 'users',
 'votes']

In [0]:
bq_assistant.head("posts_questions", num_rows=20)

          id    ...     view_count
0   23280293    ...            266
1    5787776    ...          10505
2   51899406    ...             53
3   29219176    ...            427
4   45545053    ...             30
5   49452670    ...             53
6   30640113    ...            225
7   42645929    ...            627
8   25021096    ...            216
9    7252753    ...           1577
10  15182568    ...           2445
11  31758045    ...           5916
12  51764666    ...             43
13  45134867    ...            339
14  25787394    ...           1151
15  41955896    ...             88
16  19559952    ...             91
17  30225817    ...            113
18  53535220    ...            106
19  22411997    ...             66

[20 rows x 19 columns]

In [0]:
query1 = """SELECT
  EXTRACT(YEAR FROM creation_date) AS Year,
  COUNT(*) AS Number_of_Questions,
  ROUND(100 * SUM(IF(answer_count > 0, 1, 0)) / COUNT(*), 1) AS Percent_Questions_with_Answers
FROM
  `bigquery-public-data.stackoverflow.posts_questions`
GROUP BY
  Year
HAVING
  Year > 2015 AND Year < 2020
ORDER BY
  Year;
        """
response1 = stackOverflow.query_to_pandas_safe(query1)
response1.head(10)

   Year               ...                Percent_Questions_with_Answers
0  2016               ...                                          84.6
1  2017               ...                                          82.7
2  2018               ...                                          71.0
3  2019               ...                                          63.1

[4 rows x 3 columns]

In [0]:
bq_assistant.table_schema("posts_questions")

                        name       type      mode description
0                         id    INTEGER  REQUIRED        None
1                      title     STRING  NULLABLE        None
2                       body     STRING  NULLABLE        None
3         accepted_answer_id    INTEGER  NULLABLE        None
4               answer_count    INTEGER  NULLABLE        None
5              comment_count    INTEGER  NULLABLE        None
6       community_owned_date  TIMESTAMP  NULLABLE        None
7              creation_date  TIMESTAMP  NULLABLE        None
8             favorite_count    INTEGER  NULLABLE        None
9         last_activity_date  TIMESTAMP  NULLABLE        None
10            last_edit_date  TIMESTAMP  NULLABLE        None
11  last_editor_display_name     STRING  NULLABLE        None
12       last_editor_user_id    INTEGER  NULLABLE        None
13        owner_display_name     STRING  NULLABLE        None
14             owner_user_id    INTEGER  NULLABLE        None
15              post_type_id    INTEGER  NULLABLE        None
16                     score    INTEGER  NULLABLE        None
17                      tags     STRING  NULLABLE        None
18                view_count    INTEGER  NULLABLE        None

In [0]:
query="""SELECT
  EXTRACT(MONTH FROM creation_date) AS Month,
  EXTRACT(YEAR FROM creation_date) AS Year,
  COUNT(*) AS Number_of_Questions,
  ROUND(100 * SUM(IF(answer_count > 0, 1, 0)) / COUNT(*), 1) AS Percent_Questions_with_Answers
FROM
  `bigquery-public-data.stackoverflow.posts_questions`
GROUP BY
  Month,Year
HAVING
  Year > 2016 AND Year < 2020
ORDER BY
  Month,Year;
        """ 

response1 = stackOverflow.query_to_pandas_safe(query)
response1.head(50)

    Month               ...                Percent_Questions_with_Answers
0       1               ...                                          83.8
1       1               ...                                          81.8
2       1               ...                                          67.3
3       2               ...                                          83.8
4       2               ...                                          80.5
5       2               ...                                          60.2
6       3               ...                                          83.4
7       3               ...                                          70.9
8       3               ...                                          49.1
9       4               ...                                          82.7
10      4               ...                                          70.3
11      5               ...                                          82.8
12      5               ...                                          69.5
13      6               ...                                          82.7
14      6               ...                                          69.1
15      7               ...                                          82.8
16      7               ...                                          69.0
17      8               ...                                          82.7
18      8               ...                                          69.6
19      9               ...                                          82.3
20      9               ...                                          69.4
21     10               ...                                          82.3
22     10               ...                                          68.9
23     11               ...                                          81.5
24     11               ...                                          67.6
25     12               ...                                          81.8
26     12               ...                                          67.8

[27 rows x 4 columns]